site_name: LASP2 Interface
theme:
  name: material
  icon:
    repo: fontawesome/brands/github

repo_url: https://github.com/carle13/LASP2Interface  

nav:
  - "Overview": index.md
  - "Installation": installation.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]